##### PREFIX #####
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

##### TERMINAL COLORS #####
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

##### GENERAL #####
set -g mouse on
set -g history-limit 10000
set -g aggressive-resize on
set -g window-size latest
set -g monitor-activity off
set -g renumber-windows on
set -g automatic-rename off
set -g allow-rename off
set -g focus-events on
set -g escape-time 0
set -g pane-active-border-style 'fg=magenta,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

##### SPLITS #####
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

##### VIM-TMUX-NAVIGATOR #####
unbind -n C-h
unbind -n C-j
unbind -n C-k
unbind -n C-l

##### RELOAD CONFIG #####
bind r source-file ~/.tmux.conf \; display "Tmux reloaded!"

##### CLIPBOARD INTEGRATION #####
# Using Wayland clipboard (WSLg) for tmux copy
setw -g mode-keys vi
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode y send-keys -X copy-pipe-and-cancel "wl-copy"

#### STATUS BAR ####
set-option -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux#v2.1.0'
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

# Initializeing tpm, keep it bottom
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default
